### ISSUE TITLE
Default comment uses /* */ notation, this is annoying

### ISSUE THREAD

**Issue by kootenpv** [ethereum/emacs-solidity#10]
Please just use `//`

**Comment by LefterisJP** [comment]
@kootenpv Why do you find the `/*` comment notation annoying? I had not even noticed this. I have no strong opinions on this so I can try to change it, but I am also really interested in why you find the current behaviour annoying.

**Comment by LefterisJP** [comment]
I was looking through the issues and found this old issue and I am amazed I have not addressed it yet @kootenpv. I am adding an option right now.
