### ISSUE TITLE
Syntax highlight does not consider word boundaries

### ISSUE THREAD

**Issue by aviggiano** [ethereum/emacs-solidity#13]
The word `integers` is higlighted as `int` `egers`:

![screenshot from 2017-09-10 13-00-33](https://user-images.githubusercontent.com/3029017/30250627-1166f874-9628-11e7-8986-02ae69ba967c.png)

Example contract: https://github.com/fivedogit/solidity-baby-steps/blob/master/contracts/08_basiciterator.sol

**Comment by LefterisJP** [comment]
Yes I am aware of this. Want to address it, just have not spent any time on the emacs-solidity mode in along time.

Thanks for reporting it. Hope to devote some time to do it soon. Ofcourse PRs are more than welcome.

**Comment by aviggiano** [comment]
I am not familiar with emacs modes nor with emacs lisp, but this seems a regex issue. 
I'll give it a try.

**Comment by LefterisJP** [comment]
@aviggiano That particular issue must have been fixed now. I will try to do some other additions while I am at it later today to bring the package up to speed with the latest solidity features and keywords.

**Comment by aviggiano** [comment]
@LefterisJP Thanks, it's now working properly!
