### ISSUE TITLE
zeppelin-solidity imports flycheck errors

### ISSUE THREAD

**Issue by dlebrecht** [ethereum/emacs-solidity#14]
im having trouble to cleanly import contracts from zeppelin-solidity library. 

following the instructions from Getting Started in 
https://github.com/OpenZeppelin/zeppelin-solidity

the code compiles and run correctly, but flymake flags the import as an error. 

```
import "zeppelin-solidity/contracts/ownership/Ownable.sol";
```

this is the error message:
Source "zeppelin-solidity/contracts/ownership/Ownable.sol" not found: Unknow exception in read callback (solidity-checker)

**Comment by dlebrecht** [comment]
ok, i see. if i compile the contract with ```truffle compile``` it works

but if i do it with ```solc contract.sol``` it doesnt

**Comment by LefterisJP** [comment]
Hello @dlebrecht. This is not a problem of this package of emacs-solidity but of the way that solidity handles imports. The package has no way to handle relative imports. You could add the path to the solc command with the `--allow-paths` argument and then it would work.

But the package has no way to detect this. I will add an argument to do so.

**Comment by LefterisJP** [comment]
So @dlebrecht I added a new setting to the package to provide extra arguments for solc.

In order for you to let the compiler know where zepellin is you just need to add this setting to your package configuration. 

```lisp
(setq solidity-solc-extra-args "zepellin-solidity=/home/path/to/zeppelin")
```

In the future I should try to make this kind of a per-project settting. Which means the add-on should be project-aware.

Closed by: https://github.com/ethereum/emacs-solidity/commit/b8ddfd683c3335805f0a4788244bf0d224ffc6ae

**Comment by dlebrecht** [comment]
i havent managed to use the new version of the package with any syntax highlighting. even without using the newly added parameter. the old package works for me. 

i tried like 
```
  (setq solidity-solc-path "/usr/bin/solc --allow-paths")
  (setq solidity-solc-extra-args "zepellin-solidity=/home/dlebrecht/.node/lib/node_modules/zeppelin-solidity")
```
and
```
  (setq solidity-solc-path "/usr/bin/solc")
  (setq solidity-solc-extra-args "zepellin-solidity=/home/dlebrecht/.node/lib/node_modules/zeppelin-solidity")
```
and 

```
(setq solidity-solc-path "/usr/bin/solc")
```

**Comment by LefterisJP** [comment]
@dlebrecht Hm this is strange. Can you make a new issue for this absence of syntax highlighting you are experiencing in your case? Include as many details as you can, like how you initialize the package, what commit the package is in, system details, solc version, flycheck version.
