### ISSUE TITLE
intervalNode shows also int as a keyword

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/emacs-solidity#31]
`intervalNode` key word printed as follows:

<img width="198" alt="screen shot 2018-05-02 at 10 51 15" src="https://user-images.githubusercontent.com/18537398/39511634-c4cd9c0c-4df6-11e8-9ce1-478193b6acb7.png">

I guess `int` seems as keyword as a well.

**Comment by LefterisJP** [comment]
Hello @avatar-lavventura . That's strange. Can you give me a minimal solidity contract which reproduces this behaviour with the latest emacs-solidity version?

**Comment by avatar-lavventura** [comment]
```
    function receiptCheck(intervalNode storage self, uint startTime) public
	returns (bool success)
    {
	interval storage prevNode;
	interval storage currentNode;
	interval storage prevNodeTemp;
}
```

**Comment by LefterisJP** [comment]
That's not a full contract. Please give me the full contract that fails for you. And if `interval` and `intervalNode` are structs as I assume then I made the following which does not appear to be coloured as you showed:

![2018-05-11-094704_437x351_scrot](https://user-images.githubusercontent.com/1658405/39912833-485409ac-5500-11e8-8562-724e453e3ea6.png)

**Comment by avatar-lavventura** [comment]
I have enabled `solidity-mode`.

```
pragma solidity ^0.4.17;

library Lib {
    function receiptCheck(intervalNode storage self) public
        returns (bool success)
    {
        bool     flag = false;
        uint32   addr = self.tail;
        uint32   addrTemp;
        int32    carriedSum;
        interval storage prevNode;
        interval storage currentNode;
        interval storage prevNodeTemp;
    }
}
```

<img width="421" alt="screen shot 2018-05-11 at 10 57 03" src="https://user-images.githubusercontent.com/18537398/39913315-17bbf67e-550a-11e8-9f0b-c283271d8150.png">

**Comment by avatar-lavventura** [comment]
It works now.
