### ISSUE TITLE
unrecognised option '--add-std' error after upgrading solc to 0.4.24

### ISSUE THREAD

**Issue by mandarvaze** [ethereum/emacs-solidity#33]
I recently upgraded to solc version 0.4.24, and I have started getting the following error:

`Suspicious state from syntax checker solidity-checker: Flycheck checker solidity-checker returned non-zero exit code 1, but its output contained no errors: unrecognised option '--add-std'`

This option was removed in version 0.4.22 of Solidity.
I found the following references regarding how other tools are affected. But I'm not sure if there is a fix/workaround for `emacs-solidity`

References : 
https://github.com/ethereum/solidity/issues/3984
https://github.com/ethereum/solidity/issues/3695

Solution seems to be "upgrade go-ethereum", but how does that help a "linter" functionality of `emacs-solidity` ?

**Comment by LefterisJP** [comment]
Hey @mandarvaze, thanks for reporting this. The emacs-solidity package needed updating to remove the argument
