### ISSUE TITLE
company-solidity.el not included in melpa package

### ISSUE THREAD

**Issue by hzzhang** [ethereum/emacs-solidity#39]
solidity-mode 20180912.2154 on melpa does not include company-solidity.el, and loading solidity-mode ends with an error "File mode specification error: (file-missing Cannot open load file No such file or directory company-solidity)".

**Comment by LefterisJP** [comment]
@hzzhang It seems that the owner of Melpa [added](https://github.com/melpa/melpa/commit/e9fd577cd16177bbafa799454fcd649cbebcaf26#diff-0412104ef72924b926f02943e76df818) an exclusion rule in Melpa for that file. He probably assumed that it's two different packages but now @ssmolkin1 has integrated it into this package so we need to fix this. I will make a PR to Melpa.

**Comment by stardiviner** [comment]
Seems this cause this recursive load error:
```
Initialization fails with: "Recursive load: \"/home/stardiviner/.emacs.d/elpa/solidity-mode-20180912.2154/solidity-mode.elc\", \"/home/stardiviner/.emacs.d/elpa/company-solidity-20180407.2044/company-solidity.el\", \"/home/stardiviner/.emacs.d/elpa/solidity-mode-20180912.2154/solidity-mode.elc\", \"/home/stardiviner/.emacs.d/elpa/company-solidity-20180407.2044/company-solidity.el\", \"/home/stardiviner/.emacs.d/elpa/solidity-mode-20180912.2154/solidity-mode.elc\", \"/home/stardiviner/.emacs.d/elpa/company-solidity-20180407.2044/company-solidity.el\", \"/home/stardiviner/.emacs.d/elpa/solidity-mode-20180912.2154/solidity-mode.elc\", \"/home/stardiviner/.emacs.d/elpa/company-solidity-20180407.2044/company-solidity.el\", \"/home/stardiviner/.emacs.d/elpa/solidity-mode-20180912.2154/solidity-mode.elc\""
```
Here is my config:
```elisp
(use-package solidity-mode
  :ensure t
  :no-require t)

(use-package company-solidity
  :ensure t
  :no-require t
  :config (add-hook 'solidity-mode-hook
                    (lambda ()
                      (my-company-add-backend-locally 'company-solidity))))
```

I know `company-solidity` is in `solidity-mode` now. But MELPA separated package cause this problem.

**Comment by stardiviner** [comment]
Also, the README should be updated too.

**Comment by ffimnsr** [comment]
I'm currently having problem with this one too. Getting an error message saying:

```
Recursive `require` for feature `solidity-mode`.
```
As I've looked into the issue and PR in melpa its still open.

**Comment by LefterisJP** [comment]
All right sorry for the delay. The melpa [PR](https://github.com/melpa/melpa/pull/5802#issuecomment-437635624) is now merged. 

As also reflected now in the readme [`company-solidity`](https://github.com/ethereum/emacs-solidity/tree/d6c48a1cb64d3c8a825dc0d06c839f2cacd4d289#optional-flycheck-interface) and [`solidity-flycheck`](https://github.com/ethereum/emacs-solidity/tree/d6c48a1cb64d3c8a825dc0d06c839f2cacd4d289#optional-autocompletion) are two different packages that need to be explicitly required by the user.
