### ISSUE TITLE
Change Solc to solcjs

### ISSUE THREAD

**Issue by Emiller88** [ethereum/emacs-solidity#44]
I'm having issues with flycheck and I believe it's because `solc` is not `solc-js` as a command. Not sure if it used to be `solc` or not I can't remember.

**Comment by LefterisJP** [comment]
Hey @Emiller88. These are two different binaries. `solc` is the soildity compiler. `solc-js` is a javascript wrapper. This package deals directly with `solc`.

**Comment by Emiller88** [comment]
@LefterisJP My mistake! Hopefully someone else finds this issue when they run into the same problem.
