### ISSUE TITLE
Error: Symbol’s value as variable is void: company-backends

### ISSUE THREAD

**Issue by bingen** [ethereum/emacs-solidity#46]
Trying to use `company-solidity`, I'm getting the following error: `Symbol’s value as variable is void: company-backends`

My config is:
```
;;; package --- Solidity mode
;;; Commentary:
;;; Code:

(require-package 'solidity-mode)
(require-package 'solidity-flycheck)
(require-package 'company-solidity)

(...)

(add-hook 'solidity-mode-hook
          (lambda ()
            (set (make-local-variable 'company-backends)
                 (append '((company-solidity company-capf company-dabbrev-code))
                         company-backends))))

(provide 'init-solidity)

;;; init-solidity.el ends here

```

I'm using emacs 25.2.2 on a Debian based distribution.

**Comment by LefterisJP** [comment]
Hey @bingen 

Apologies for the rather late response, somehow the notification for this issue fell through the cracks.

I tried to reproduce your issue with the latest solidity mode and I don't seem to be able to. Perhaps there is something else that messes with the `company-backends` variable in your configuration?

Can you start emacs with `--debug-init` and try to get a stack trace to see if you can get more information how this problem is caused for you?

**Comment by bingen** [comment]
Hi @LefterisJP ,

I started with debug (like this `/usr/bin/emacs --debug-init contracts/Court.sol`) and the only thing I see is this message:
```
File mode specification error: (void-variable company-backends)
```
Nothing else.

The version of company-mode I'm using is `20181117.1518` and solidity mode version is `20190302.909` (I was using `20190130.2250`, but I updated it just in case with same result).

Thanks for your help!

**Comment by LefterisJP** [comment]
Hey @bingen 

I tried again to reproduce your issue and I could not. The only way to go forward with the issue would be to for you to try and debug your init configuration and see how you configure the solidity package and also how you configure company. Something in the way they are configured leads to this problem.

**Comment by bingen** [comment]
Ok, cool. Not an emacs expert, but I'll try. Thanks for your help!!

**Comment by bingen** [comment]
I finally figured it out. I was not loading comany init file in my main emacs init file. :man_facepalming: 
Sorry for the confusion, and thanks again for your help.

**Comment by LefterisJP** [comment]
@bingen Very happy you figured it out :+1:
