### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/emacs-solidity#48]
I have add following lines into my `.emacs` file but emacs-solidity does not work.

```
(require 'solidity-mode)
(require 'solidity-flycheck)
(setq solidity-solium-path "/Users/avatar/.npm-packages/lib/node_modules/solium/bin/solium.js")
(setq solidity-solc-path "/Users/avatar/.npm-packages/lib/node_modules/solc/solcjs")
(setq solidity-flycheck-solc-checker-active t)
(setq solidity-flycheck-solium-checker-active t)
```

**Comment by LefterisJP** [comment]
Hello! Can you provide some more info? What is the error? How did you install the package? 

Also I can see that you are trying to use `solcjs`. This emacs package works only with the normal `solc` binary, not the js wrapper. Same thing for `solium`.

**Comment by avatar-lavventura** [comment]
The way install the package:
`M-x package install solidity-mode` RET

```
$ which solc
/usr/local/bin/solc
```

I have updated `solidity-solc-path` with the notmal `solc` binary: `(setq solidity-solc-path "/usr/local/bin/solc")`

=> Actually I do not get any error but nothing also happens when I open `.sol` file using emacs.

**Comment by LefterisJP** [comment]
I would really like to help you but I can not do that without knowing more about your configuration or what is written in the `*Messages*` buffer when a solidity file is opened.

**Comment by LefterisJP** [comment]
@avatar-lavventura looking at your other issue it seems that you managed to find what was wrong for you here? Can I close this issue?

**Comment by avatar-lavventura** [comment]
Sure, I can provide more information if its required on other issue.
