### ISSUE TITLE
Unable to make  `solidity-flycheck-solc` work

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/emacs-solidity#52]
I am unable to make  `solidity-flycheck-solc` work. I am not sure what I am doing wrong.

```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.6.0+commit.26b70077.Darwin.appleclang
$ which solc
/usr/local/bin/solc
```

-----

I have following setup in `.emacs` file:

```emacs
(require 'flycheck)
(setq solidity-solc-path "/usr/local/bin/solc")
(require 'solidity-flycheck)
(require 'solidity-mode)
(setq flycheck-solidity-solc-addstd-contracts t)
(setq solidity-flycheck-solc-checker-active t)

(custom-set-variables
 '(package-selected-packages
   (quote
    (solidity-flycheck solidity-mode use-package flymake-python-pyflakes flycheck undo-tree jedi dumb-jump))))

(add-hook 'after-init-hook #'global-flycheck-mode)

```

=> ```flycheck-verify-setup``` and this is what I got:

```emacs
Syntax checkers for buffer eBlocBroker.sol in solidity-mode:

There are no syntax checkers for this buffer!

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 31
Emacs version:    26.3
System:           x86_64-apple-darwin19.0.0
Window system:    nil

```

**Comment by LefterisJP** [comment]
Hey @avatar-lavventura you need to add a
```elisp
(require 'solidity-flycheck)
```

before 
```elisp
(require 'solidity-mode)
```

as per the [readme](https://github.com/ethereum/emacs-solidity#optional-flycheck-interface).

Does this solve your problem? Rememer to re-byte-compile any files before trying again.

**Comment by avatar-lavventura** [comment]
I have done it but it did'nt solve the problem :(

**Comment by LefterisJP** [comment]
Did you make sure to byte recompile your emacs .el files? With `M-x flycheck-select-checker` do you see the `solidity-checker` in there? If not then that mean that for some reason the `'solidity-flycheck` module is not loaded. Any errors in your `*Messages*` buffer?

**Comment by avatar-lavventura** [comment]
I have install it by using `M-x`, `install packages` => `solidity-flycheck` \enter

=> `solidity-checker` does not show up 

=> `emacs -nw Test.sol` open without having any error message.

**Comment by avatar-lavventura** [comment]
`M-x`, `install packages` => `solidity-flycheck` \enter

Does not install `company-solidity`, so without that on initial install `solidity-checker` shows up. But when I manually put `company-solidity`, `solidity-checker`  does not show up and says a suspicious behavior

**Comment by avatar-lavventura** [comment]
I have install everything from scratch but still flycheck does not work:

=> flycheck-verify-setup and this is what I got:

```
Syntax checkers for buffer Test.sol in solidity-mode:

  solidity-checker
    - may enable: yes
    - predicate:  t
    - executable: Found at /usr/local/bin/solc

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 31
Emacs version:    26.3
System:           x86_64-apple-darwin19.0.0
Window system:    nil

```

**Comment by LefterisJP** [comment]
You don't need to use `(load ...)`. `(require ...) is better for this.

And are you 100% sure it's not activated? You got both activated judging from the pasted output of `flycheck-verify-setup`.

Why are you adding them manually to the flycheck checkers? If you got the `(setq solidity-flycheck-solc-checker-active t)` before requiring solidity flycheck, then that should be done automatically. And also the callback to run flycheck with that checker in .sol files.

Here take a look at my configuraiton:

https://github.com/LefterisJP/.emacs/blob/ccec8c5e33c1afc4755dd2cd11f1a8d9572fe1e4/el-get-user/init_files/init-solidity-mode.el#L6-L20

**Comment by avatar-lavventura** [comment]
On both approaches, `solidity-mode` works where the font color changes. But `flycheck` does not work like it should do on python files.

I have tried two different approach.

1)
 `M-x` => `package-install` => `solidity-mode`
`M-x` => `package-install` => `solidity-flychecker`
Installs into `/elpha/solidity-flycheck-0.1.9`, but the file's version shows up as `0.1.0`. So in this approach flycheck does not work.

2) I install through `el-get`, so it installs into `el-get/solidity-mode` where when I try to use `(require ...)` I get an error where it cannot find the file, so I use `(load ...)`

**Comment by LefterisJP** [comment]
If you see `solidity-checker` when you do `flycheck-verify-setup` it means that it's activated and loaded from `solidity-mode` side.

If it does not work for your from that point on I don't know what could be wrong. Perhaps something is wrong with your flycheck setup.

**Comment by avatar-lavventura** [comment]
I can see `solidity-checker`.

I didn't change any flycheck setup :/ 

I added following line as well which didn't help `(add-hook 'after-init-hook #'global-flycheck-mode)
`

**Comment by avatar-lavventura** [comment]
Seems like working for only Stack too deep:

```
Suspicious state from syntax checker solidity-checker: Flycheck checker solidity-checker returned non-zero exit code 1, but its output contained no errors: Compiler error: Stack too deep, try removing local vari\
ables.
   --> /Users/alper/eBlocBroker/contract/contracts/flycheck_eBlocBroker.sol:208:111:
    |
208 |  ... .jobID].mul(args.executionDuration[args.jobID])).add(info.priceDataTransfe ...
    |                                         ^^^^


Try installing a more recent version of solidity-checker, and please open a bug report if the issue persists in the latest release.  Thanks!
```

**Comment by LefterisJP** [comment]
@avatar-lavventura Solidity checker essentially calls `solc` and tries to see what errors that returns. Some times only one error is returned so that's what the solidity checker will show you. Once you fix it then more errors will be shown.

But from your report I see that there may be a problem of parsing the results of solc compile for your case.

Can you tell me what version of solc you are using and add here the `.sol` file you are compiling? This way I can debug it and see what's wrong.

**Comment by avatar-lavventura** [comment]
```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.6.0+commit.26b70077.Darwin.appleclang
```

**=>** Does it also able to do style check (https://solidity.readthedocs.io/en/v0.6.0/style-guide.html) like Python does for `PEP 8`?

**Comment by LefterisJP** [comment]
@avatar-lavventura I also need the solidity file that is throwing this error.

No style checks. I think the solium tool does style checks. But I have not used it myself.

**Comment by avatar-lavventura** [comment]
=> solium tool also does not work :(

Here is a simple example:

```
pragma solidity ^0.6.0;

contract Test {
    mapping(address => bytes32) public Countries;

	function get()
	external
	view
	returns (uint)
    {
     	uint a = 299;
	uint b = 150;
	uint c;
	uint c1;
	uint c2;
        uint c3;
	uint c4;
	uint c5;
        uint c6;
        uint c7;
        uint c8;
        uint c9;
        uint c10;
        uint c11;
        uint c12;
        uint c13;

	return a / b;

    }

}
```

Error message:
```
Suspicious state from syntax checker solidity-checker: Flycheck checker solidity-checker returned non-zero exit code 1, but its output contained no errors: Compiler error: Stack too deep, try removing local vari\
ables.
  --> /Users/alper/eBlocBroker/contract/contracts/flycheck_Test.sol:28:14:
   |
28 |            return a / b;
   |                   ^


Try installing a more recent version of solidity-checker, and please open a bug report if the issue persists in the latest release.  Thanks!
```

**Comment by LefterisJP** [comment]
@avatar-lavventura All right I can hopefully fix this error. I tried it in my setup and it is reproducible. The error is due to changes in the way the output is done in `solc` versions <= 0.6.1.

The first is from solc 0.6.1 and the second from solc 0.5.7:

![2020-01-13-140927_556x205_scrot](https://user-images.githubusercontent.com/1658405/72258427-5adb8780-360e-11ea-9f32-6d2d6938ee92.png)

The solidity mode flychecker integration expects the output to be in the first 0.5.7 way.

Give me some time. This is something I can help you with and fix.

**Comment by avatar-lavventura** [comment]
Thank you @LefterisJP . There is no rush so please take your time.

=> Does `solium style check` works on your end? When this error is fixed, would it also let solium style checks to be work?

**Comment by LefterisJP** [comment]
@avatar-lavventura I have actually never used solium myself as I don't like its style suggestions. It was added by @rowanthorpe in this PR: https://github.com/ethereum/emacs-solidity/pull/35

If I find some time I will check it out later. First solc flycheck definitely needs fixing.

**Comment by LefterisJP** [comment]
@avatar-lavventura I pushed a patch to fix this and it seems to work locally. Tell me how it is for you.

**Comment by avatar-lavventura** [comment]
How could I pull the patch? I have deleted everything and reinstall using 'el-get`, but seems like didn't get the patch.

**Comment by avatar-lavventura** [comment]
Also for `solium` I get some output like this:

```
tion^[[23m
^[[1m  567:2  ^[[22m   ^[[31merror  ^[[39m    Only use indent of 8 spaces.     \
                                                                               \
                                                                   ^[[3mindenta\
tion^[[23m
^[[1m  569:1  ^[[22m   ^[[31merror  ^[[39m    Only use indent of 8 spaces.     \
                                                                               \
                                                                   ^[[3mindenta\
tion^[[23m
^[[1m  569:1  ^[[22m   ^[[33mwarning  ^[[39m  Provide an error message for requ\
ire()                                                                          \
                                                                   ^[[3merror-r\
eason^[[23m
^[[1m  571:1  ^[[22m   ^[[33mwarning  ^[[39m  Line contains trailing whitespace\
                                                                               \
                                                                   ^[[3mno-trai\
ling-whitespace^[[23m
^[[1m  573:2  ^[[22m   ^[[33mwarning  ^[[39m  Line contains trailing whitespace\
                                                                               \
                                                                   ^[[3mno-trai\
ling-whitespace^[[23m
^[[1m  577:2  ^[[22m   ^[[33mwarning  ^[[39m  Line contains trailing whitespace\

Try installing a more recent version of solium-checker, and please open a bug r\
eport if the issue persists in the latest release.  Thanks!
```

**Comment by LefterisJP** [comment]
Hey @avatar-lavventura for solium check please make another issue and paste your solium version and an example .sol file. Then I can look at it as a separate issue.

**Comment by LefterisJP** [comment]
> I have deleted everything and reinstall using el-get, but seems like didn't make any change (like I am still getting the same compiler error message

That's odd. It works for me. Can you go into the source file of `solidity-flycheck.el and see if it matches what is shown in latest master here? Can you make sure no remaining byte compiled files from before are left?

**Comment by avatar-lavventura** [comment]
I also removed solidity-* folders under `elpha`.

```
rm -rf ~/.emacs.d/el-get/solidity-mode
```
Then inside emacs `el-get-install` => `solidity-mode`.

I assume it is update, inside `solidity-flycheck.el` file under `~/.emacs.d/el-get/solidity-mode`  I can see:

``
defun solc-gt-0.6.0 ()
  "Return `t` if solc >= 0.6.0 and `nil` otherwise."
``

----

> Can you make sure no remaining byte compiled files from before are left?

Any advice for this?

**Comment by avatar-lavventura** [comment]
For example with the update version, should I receive any error for wrongly typle keywords such as:

=> `uin helloWorld` // `t` is missing
=> `publi` // `c` is missing

On my end nothing happens.

**Comment by LefterisJP** [comment]
And you get absolutely nothing in the **Messages** buffer? It's hard for me to help since with the new version it works fine for me.

**Comment by avatar-lavventura** [comment]
Unfortunetly nothing shows up in the Messages buffer :-(

I only get `Compiler error: Stack too deep,` error if there is one right after doing saving the file.

**Comment by avatar-lavventura** [comment]
My final setup is as follows:

```
(require 'flycheck)
(setq solidity-solc-path "/usr/local/bin/solc") ;; This better be set before requiring solidity mode.
(setq solidity-solium-path "/Users/alper/.npm-packages/bin//solium")

(setq solidity-flycheck-solc-checker-active t)
(setq solidity-flycheck-solium-checker-active t)

(require 'solidity-flycheck)
(require 'solidity-mode)

(setq solidity-comment-style 'slash)

(add-hook 'solidity-mode-hook
        (lambda ()
        (set (make-local-variable 'company-backends)
                (append '((company-solidity company-capf company-dabbrev-code))
                        company-backends))))

(provide 'init-solidity-mode)
(setq-default flycheck-flake8-maximum-line-length 200)

(add-hook 'c++-mode-hook 'flycheck-mode)
(add-hook 'web-mode-hook 'flycheck-mode)
(add-hook 'json-mode-hook 'flycheck-mode)
(add-hook 'solidity-mode-hook 'flycheck-mode)
```
