### ISSUE TITLE
solc `--old-reporter` flag removed in solc 0.8.0

### ISSUE THREAD

**Issue by mdunnio** [ethereum/emacs-solidity#62]
I'm receiving this error message:

```
Suspicious state from syntax checker solidity-checker: Flycheck checker solidity-checker returned 1, but its output contained no errors: unrecognised option '--old-reporter'
```
It was removed here: https://github.com/ethereum/solidity/pull/10167

Not sure how to reconcile solidity-checker with the new output.

**Comment by LefterisJP** [comment]
Oh hey @mdunnio thanks for the issue. I don't have much time to maintain this repo much lately. If you have any elisp skills perhaps you could help debug this and provide a fix for the problem?
