### ISSUE TITLE
Installation error: "/usr/bin/solc"' is a malformed function

### ISSUE THREAD

**Issue by tuxayo** [ethereum/emacs-solidity#8]
`/usr/bin/solc` exists but it seems that there something wrong related that prevents the installation from finishing.

```
Leaving directory `/home/victor/.emacs.d/elpa/solidity-mode-20160426.31'

Compiling file /home/victor/.emacs.d/elpa/solidity-mode-20160426.31/solidity-mode-pkg.el at Fri Apr 29 13:21:06 2016
Entering directory `/home/victor/.emacs.d/elpa/solidity-mode-20160426.31/'

Compiling file /home/victor/.emacs.d/elpa/solidity-mode-20160426.31/solidity-mode.el at Fri Apr 29 13:21:06 2016
solidity-mode.el:383:1:Warning: `"/usr/bin/solc"' is a malformed function
solidity-mode.el:383:1:Warning: `(error line-start (file-name) ":" line ":"
    column ":" " Error: " (message))' is a malformed function
solidity-mode.el:386:28:Warning: reference to free variable `solidity'
solidity-mode.el:388:31:Warning: reference to free variable `source-inplace'
solidity-mode.el:391:12:Warning: reference to free variable `solidity-mode'
solidity-mode.el:393:17:Warning: reference to free variable
    `flycheck-checkers'
solidity-mode.el:393:17:Warning: assignment to free variable
    `flycheck-checkers'
solidity-mode.el:395:30:Warning: assignment to free variable
    `flycheck-solidity-executable'

In end of data:
solidity-mode.el:399:1:Warning: the function `flycheck-define-checker' is not
    known to be defined.

Compiling no file at Fri Apr 29 13:24:20 2016

```

emacs 24.5
Spacemacs 0.105.19
solc 0.3.2-81ae2a78

**Comment by tbrooke** [comment]
I get the same errors in emacs 25 with spacemacs  -  solidity-mode does not load

**Comment by tbrooke** [comment]
I am using Spacemacs and Emacs v 25 

I was receiving this error message (see [Issue 8](https://github.com/ethereum/emacs-solidity/issues/8))
```

Compiling file /home/victor/.emacs.d/elpa/solidity-mode-20160426.31/solidity-mode.el at Fri Apr 29 13:21:06 2016
solidity-mode.el:383:1:Warning: `"/usr/bin/solc"' is a malformed function
solidity-mode.el:383:1:Warning: `(error line-start (file-name) ":" line ":"
    column ":" " Error: " (message))' is a malformed function
solidity-mode.el:386:28:Warning: reference to free variable `solidity'
solidity-mode.el:388:31:Warning: reference to free variable `source-inplace'
solidity-mode.el:391:12:Warning: reference to free variable `solidity-mode'
solidity-mode.el:393:17:Warning: reference to free variable
    `flycheck-checkers'
solidity-mode.el:393:17:Warning: assignment to free variable
    `flycheck-checkers'
solidity-mode.el:395:30:Warning: assignment to free variable
    `flycheck-solidity-executable'
```

I commented out the following and it works fine, but I guess I don't have flycheck:

```

;;; --- interface with flycheck if existing ---
(when (require 'flycheck nil 'noerror)
  ;; add dummy source-inplace definition to avoid errors
  (defvar source-inplace)
  ;; add a solidity mode callback to set the executable of solc for flycheck
  ;; define solidity's flycheck syntax checker
  (flycheck-define-checker solidity-checker
    "A Solidity syntax checker using the solc compiler"
    :command ("/usr/bin/solc" source-inplace)
    :error-patterns
    ((error line-start (file-name) ":" line ":" column ":" " Error: " (message)))
    :modes solidity-mode
    :predicate (lambda () (eq major-mode 'solidity-mode)))
  (add-to-list 'flycheck-checkers 'solidity-checker)
  (add-hook 'solidity-mode-hook
            (lambda () (setq flycheck-solidity-executable solidity-solc-path))))

```

**Comment by tbrooke** [comment]
I thought they were just compiler warnings - I retried the melpa version and it still doesn't load - and I went back to my version with flycheck commented out and it does work: https://github.com/tbrooke/emacs-solidity and it does

Spacemacs version 0.200.1
Emacs 25.1.1

**Comment by LefterisJP** [comment]
I believe this latest commit must have fixed the issue. It at least no longer shows the warnings when compiling in the normal Emacs.

@tbrooke Can you check and report back and tell me if it works? Note: Spacemacs uses Melpa and as such it may take a while until the commit is included in the latest Melpa Build. Best way to make sure is to check [this](http://melpa.org/#/solidity-mode) link and make sure that the melpa version is NOT `20161013.203`

**Comment by tbrooke** [comment]
Still 20161013.203 - I'lll try it later -- BTW I did look at spacemacs and found a lot of discussion about how they use flycheck in an unconventional way -- I didn't follow it all 
     https://github.com/syl20bnr/spacemacs/issues/4782

**Comment by LefterisJP** [comment]
@tbrooke Had you have time to check if this is still an issue?

**Comment by tbrooke** [comment]
It enters solidity mode and the syntax highlighting works but I get the following message - which it just a warning


Compiling no file at Wed Oct 26 19:51:04 2016
Warning (bytecomp): ‘"/usr/bin/solc"’ is a malformed function
Warning (bytecomp): ‘(error line-start (file-name) ":" line ":" column ":" " Error: " (message))’ is a malformed function

**Comment by juergenhoetzel** [comment]
> Compiling no file at Wed Oct 26 19:51:04 2016
> Warning (bytecomp): ‘"/usr/bin/solc"’ is a malformed function
> Warning (bytecomp): ‘(error line-start (file-name) ":" line ":" column ":" " Error: " (message))’ is a malformed function

Because the macro `flycheck-define-checker` is not defined at compile time, the the lisp reader tries to compile `("/usr/bin/solc" source-inplace)` as ***invalid*** function application.

Possible workarounds: 
1. define a dummy `flycheck-define-checker` macro in case `flycheck` is not available
2. Split the flycheck functionality in a seperate package
